"""triage-session

Revision ID: c16dbf9413f9
Revises: 
Create Date: 2026-06-21 06:57:14.323510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c16dbf9413f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triage_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('patient_sex', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('patient_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('symptoms_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symptoms_english', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_entities_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vitals_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vitals_anomalies_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triage_result_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triage_score', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_session_patient_phone'), 'triage_session', ['patient_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triage_session_patient_phone'), table_name='triage_session')
    op.drop_table('triage_session')
    # ### end Alembic commands ###
